#!/usr/bin/env bash
# generate some files and install base packages on new install

echo 'generate dwm lightdm launcher'
cat<<EOF > /tmp/dwm.desktop
[Desktop Entry]
Encoding=UTF-8
Name=dwm
Comment=Dynamic window manager
Exec=dwm
Icon=dwm
Type=XSession
EOF
sudo chown root:root /tmp/dwm.desktop
sudo  mv /tmp/dwm.desktop /usr/share/xsessions/dwm.desktop

echo 'enable tap to touch'
cat<<EOF > /tmp/30-touchpad.conf
Section "InputClass"
    Identifier "touchpad"
    Driver "libinput"
    MatchIsTouchpad "on"
    Option "Tapping" "on"
    Option "TappingButtonMap" "lmr"
EndSection
EOF
sudo chown root:root /tmp/30-touchpad.conf
sudo  mv /tmp/30-touchpad.conf /etc/X11/xorg.conf.d/30-touchpad.conf

echo 'installing packages'
sudo pacman -S  \
    arandr autoconf automake base-devel bash-completion clang conky \
    ctags dmenu dunst fd feh file-roller fzf gnome-calculator \
    inotify-tools inotify-tools lua51 luajit lxappearance-gtk3 m4 make \
    matcha-gtk-theme ncdu nodejs npm pa-applet \
    papirus-maia-icon-theme pass patch pavucontrol perl-rename pkgconf \
    ripgrep rofi st stow sxiv thunar tmux trayer tree udiskie vim vlc \
    xclip xcursor-breeze xdotool xorg-xbacklight xorg-xev xorg-xmodmap \
    xorg-xkill xorg-xsetroot yay zathura zathura-pdf-mupdf \
    moreutils renameutils python-pip ninja ccls cmake

echo 'installing language servers / linters / formatters'
sudo pacman -S shellcheck tidy 
pip install yamllint pylint cpplint jedi-language-server
pip install --pre vim-vint  # version 4.3
npm i -g bash-language-server typescript tsc \
    typescript-language-server vim-language-server yaml-language-server \
    diagnostic-languageserver http-server livereload eslint tsc csslint \
    markdownlint stylelint standard prettier vscode-langservers-extracted
./files/bin/sumneko_setup



echo "installing dwm and st"
sudo pacman -Rns st-manjaro
cd "$HOME"/Desktop || exit
git clone https://github.com/brenopacheco/dwm && cd dwm && \
    sudo make clean install && cd ../
git clone https://github.com/brenopacheco/st && cd st && \
    sudo make clean install && cd ../

echo 'installing yay packages'
# yay gotop-bin htop-vim-git lf-bin neovim-nightly-bin rtl8821ce-dkms-git
yay -S gotop-bin htop-vim-git lf-bin


echo "setting up udev rules for logitech keyboard"
echo 'ACTION=="bind", SUBSYSTEM=="hid", RUN+="/opt/bin/k380.sh %p"' | sudo tee /etc/udev/rules.d/50-k380.rules
sudo mkdir -p /opt/bin
cat<<EOF | sudo tee /opt/bin/k380.sh
#!/bin/sh
exec >>/tmp/k380-udev.log 2>&1
if [ "\$HID_NAME" = 'Keyboard K380' ]; then
  echo "RUN: at \$(date) by \$(whoami) act \$ACTION - HID_NAME: \$HID_NAME - Loading Xmodmap"
  export DISPLAY=:0
  export HOME=/home/breno
  xmodmap ~/.Xmodmap
  setxkbmap -model pc105 -layout gb
fi
if [ "\$HID_NAME" = 'Adv360 Pro' ]; then
  echo "RUN: at \$(date) by \$(whoami) act \$ACTION - HID_NAME: \$HID_NAME - Loading Xmodmap-adv360"
  export DISPLAY=:0
  export HOME=/home/breno
  setxkbmap -model pc104 -layout us
fi
EOF
sudo chmod +x /opt/bin/k380.sh /etc/udev/rules.d/50-k380.rules

cat<<EOF | sudo tee /etc/X11/xorg.conf.d/00-keyboard.conf
Section "InputClass"
        Identifier "system-keyboard"
        MatchIsKeyboard "on"
        Option "XkbLayout" "us"
        Option "XkbModel" "pc104"
EndSection
EOF
