# File:   ${expand("%:t")}
# Author: ${expand("$USER")}
# Email:  ${$USER . "@" . hostname()}
# Date:   ${strftime("%c")}

# trigger: <C-j>

# http://localhost:9200
# GET /api/nodes?q=abc

# http://localhost:9200
# POST /testindex/testtype
# {
#   "key": "new key",
#   "value": "new value"
# }


# http://localhost:9200
# POST /testindex/_bulk?pretty
# @data.sample.json

# http://localhost:9200
# GET /testindex/testtype/_search?pretty
# q=+name:FOO +value:(FOO BAR)

# http://localhost:9200
# GET /testindex/testtype/_search
# pretty&
# q=+name:FOO +value:(FOO BAR)

# http://localhost:9200
# DELETE /testindex?pretty

# http://localhost:9200
# HEAD /testindex

# vim: set ft=rest
