openapi: 3.0.0
servers:
  url: ...
info:
  title: ...
  version: 1.0.1
  description: ...
  contact:
    name: ...
    email: ...
    url: ...
    license:
      name: the MIT license (MIT)
      url: https://...

paths:
  /users/{id}:
    summary: ...
    description: ...
    get:
      operationId: ...
      responses:
        200:
          description: ...
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
      externalDocs:
        description: ...
        url: https://...

components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        required:
          - id
          - name
