- name: Configure ssh known_hosts
  lineinfile:
    path: ~/.ssh/known_hosts
    line: "{{ item }}"
    create: yes
    state: present
  loop: 
    - "github.com ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOMqqnkVzrm0SdG6UOoqKLsabgH5C9okWi0dh2l9GKJl"
    - "github.com ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCj7ndNxQowgcQnjshcLrqPEiiphnt+VTTvDP6mHBL9j1aNUkY4Ue1gvwnGLVlOhGeYrnZaMgRK6+PKCUXaDbC7qtbW8gIkhL7aGCsOr/C56SJMy/BCZfxd1nWzAOxSDPgVsmerOBYfNqltV9/hWCqBywINIR+5dIg6JTJ72pcEpEjcYgXkE2YEFXV1JHnsKgbLWNlhScqb2UmyRkQyytRLtL+38TGxkxCflmO+5Z8CSSNY7GidjMIZ7Q4zMjA2n1nGrlTDkzwDCsw+wqFPGQA179cnfGWOWRVruj16z6XyvxvjJwbz0wQZ75XK5tKSb7FNyeIEs4TT4jk+S4dhPeAUC5y+bDYirYgM4GC7uEnztnZyaVWQ7B381AK4Qdrwt51ZqExKbQpTUNn+EjqoTwvqNj4kqx5QUCI0ThS/YkOxJCXmPUWZbhjpCg56i+2aB6CmK2JGhn57K5mj0MNdBXA4/WnwH6XoPWJzK5Nyu2zB3nAZp+S5hpQs+p1vN1/wsjk="
    - "github.com ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBEmKSENjQEezOmxkZMy7opKgwFB9nkt5YRrYMjNuG5N87uRgg6CLrbo5wAdT/y6v0mKV0U2w0WZ2YB/++Tpockg="
  loop_control:
    label: "{{ item.split(' ')[0] }} {{ item.split(' ')[1] }}"


- name: Clone repositories
  git:
    repo: "{{ item.repo }}"
    dest: "{{ item.dest }}"
    update: false
    force: false
    clone: true
  loop:
    - { repo: "git@github.com:brenopacheco/.dotfiles.git",       dest: ".dotfiles" }
    - { repo: "git@github.com:brenopacheco/.password-store.git", dest: ".password-store" }
    - { repo: "git@github.com:brenopacheco/notes.git",           dest: "notes" }
    - { repo: "git@github.com:brenopacheco/dwm-fork.git",        dest: "git/dwm-fork" }
    - { repo: "git@github.com:brenopacheco/st-fork.git",         dest: "git/st-fork" }
    - { repo: "git@github.com:brenopacheco/dmenu-fork.git",      dest: "git/dmenu-fork" }
    - { repo: "git@github.com:brenopacheco/slstatus-fork.git",   dest: "git/slstatus-fork" }
  loop_control:
    label: "{{ item.repo }}"
