---
- name: Enable and start global systemd services
  ansible.builtin.systemd:
    name: "{{ item }}"
    enabled: yes
    state: started
  loop:
    - bluetooth
    - cronie
    - docker
    - lightdm
    - sshd


- name: Enable and start user systemd services
  become_user: "{{ username }}"
  ansible.builtin.systemd:
    name: "{{ item }}"
    enabled: yes
    state: started
    scope: user
  loop:
    - gpg-agent.target
