-- vim.cmd.colorscheme("catppuccin")
-- vim.cmd.colorscheme("catppuccin-latte")
-- vim.cmd.colorscheme("catppuccin-frappe")
-- vim.cmd.colorscheme("catppuccin-macchiato")
vim.cmd.colorscheme("catppuccin-mocha")
