#!/bin/bash

exec </dev/tty

echo "netrc: checking email/netrc configuration..."

email=$(git config --local --get user.email)
if [ -n "$email" ]; then
	exec ~/.config/git/switch-netrc.sh
fi

email=$(git config --global --get user.email)
if [ -z "$email" ]; then
	echo "netrc: no local or global email is set in .git/config" >&2
	exit 1
fi

echo "netrc: local email is not set"
read -rp "netrc: set local $email? (y/n): " confirm
if [[ "$confirm" =~ ^[Yy]$ ]]; then
	git config --local user.email "$email"
	exec ~/.config/git/switch-netrc.sh
fi

echo "netrc: run git config --local user.email <email>" >&2
exit 1
