-- File: lua/treesitter.lua
-- Description: treesitter configuration file

local supported = {
	-- "d",
	-- "ocamllex",
	-- "swift",
	-- "teal",
	-- "tree-sitter-query",
	"bash",
	"c",
	"clojure",
	"cmake",
	"comment",
	"commonlisp",
	"cpp",
	"c_sharp",
	"css",
	"dart",
	"diff",
	"dockerfile",
	"dot",
	"elixir",
	"elm",
	"erlang",
	"fennel",
	"gitattributes",
	"gitcommit",
	"git_config",
	"gitignore",
	"git_rebase",
	"go",
	"gomod",
	"gosum",
	"graphql",
	"groovy",
	"html",
	"http",
	"ini",
	"java",
	"javascript",
	"jq",
	"jsdoc",
	"json",
	"json5",
	"julia",
	"kotlin",
	"latex",
	"lua",
	"luadoc",
	"luau",
	"make",
	"markdown",
	"markdown_inline",
	"mermaid",
	"meson",
	"ninja",
	"nix",
	"norg",
	"ocaml",
	"ocaml_interface",
	"odin",
	"org",
	"passwd",
	"perl",
	"php",
	"prisma",
	"proto",
	"pug",
	"python",
	"r",
	"racket",
	"regex",
	"rst",
	"ruby",
	"rust",
	"scala",
	"scheme",
	"scss",
	"solidity",
	"sql",
	"svelte",
	"sxhkdrc",
	"terraform",
	"toml",
	"tsx",
	"twig",
	"typescript",
	"v",
	"vala",
	"vim",
	"vimdoc",
	"vue",
	"yaml",
	"zig",
}

require("nvim-treesitter.configs").setup({
	ensure_installed = supported,
	indent = { enable = true },
	highlight = { enable = true, additional_vim_regex_highlighting = { "org", "markdown" } },
	incremental_selection = { enable = false },
	textobjects = {
		select = {
			enable = true,
			lookahead = true, -- Automatically jump forward to textobj, similar to targets.vim
			keymaps = {
				["af"] = "@function.outer",
				["if"] = "@function.inner",
				["ac"] = "@class.outer",
				["ic"] = "@class.inner",
			},
		},
	},
	playground = {
		enable = true,
		disable = {},
		updatetime = 25, -- Debounced time for highlighting nodes in the playground from source code
		persist_queries = false, -- Whether the query persists across vim sessions
		keybindings = {
			toggle_query_editor = "o",
			toggle_hl_groups = "i",
			toggle_injected_languages = "t",
			toggle_anonymous_nodes = "a",
			toggle_language_display = "I",
			focus_language = "f",
			unfocus_language = "F",
			update = "R",
			goto_node = "<cr>",
			show_help = "?",
		},
	},
})
